### ISSUE TITLE
"ButlerSpyglass.logLevel" is not defined

### ISSUE THREAD

**Issue by ravinderkommerelli** [ptarmiganlabs/butler-spyglass#45]
**Describe the bug**

D:\QS-Buttler-Spy-Glass\node_modules\config\lib\config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "ButlerSpyglass.logLevel" is not defined
    at Config.get (D:\QS-Buttler-Spy-Glass\node_modules\config\lib\config.js:203:11)
    at Object.<anonymous> (D:\QS-Buttler-Spy-Glass\src\logger.js:25:23)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (D:\QS-Buttler-Spy-Glass\src\extract_app.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)

**To Reproduce**
Node index.js

**Expected behavior**

**Screenshots**

**Describe environment:**
 - OS: [e.g. Windows Server 2016, 
 - Containerisation -no
 - Version of Butler Spyglass used - 1.2.1
 - Command used to start Butler Spyglass - Node Index.js

**Config file(s)**
What's the content of the config file(s) you use?
Please make sure to remove all sensitive information before posting it here.

**Additional context**

**Comment by mountaindude** [comment]
First: It's been a while since this project was updated. But it should still be working.

It's difficult/impossible to tell what's causing your problem without knowing a) what your config file looks like and b) what command you used to start Butler Spyglass with.

If I am to make a guess I'd however first verify that you have defined the `NODE_ENV` environment variable and that it contains the name of your YAML config file.

For example, if `NODE_ENV` is set to `my-config-file`, Butler Spyglass will look for a config file named `my-config-file.yaml`.
Failing to set NODE_ENV would probably result in an error similar to the one you experience.

**Comment by mountaindude** [comment]
@ravinderkommerelli 

I have spent some time bringing Butler Spyglass up to date. 
This includes the documentation that was quite outdated...

Please note though that some breaking changes were done (thus the move of version number to 2.x). 
Specifically the config file format was changed slightly - you thus need to update your config file if you have used Butler Spyglass already.

Latest version as of this writing is [2.0.2](https://github.com/ptarmiganlabs/butler-spyglass/releases/tag/butler-spyglass-v2.0.2), give it a try!
